### ISSUE TITLE
Regarding GET db-session cookie from the SSO request

### ISSUE THREAD

**Issue by Luke265** [informagico/FusionSolar-API-RE#1]
To get db-session cookie, just disable redirects in this request call https://github.com/informagico/FusionSolar-API-RE/blob/3383fee7e9ad6bb0e4f2a822f2f7e1ef15c5682e/src/app.js#L103-L103 , not sure how to do in axios, probably setting `maxRedirects` to zero might work

**Comment by informagico** [comment]
Uh, that's cool thank you! Will take a look in the next days 🤘

**Comment by informagico** [comment]
@Luke265 it is indeed working! Thanks for the suggestion 👍 
Hope to find time to implement the rest in the near future, but feel free to fork and contribute ❤️
